param(
    [Parameter(Mandatory = $true)][string]$TaskId,
    [string]$Owner = "unassigned",
    [string]$Root = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

$taskRoot = Join-Path $Root "workspaces/tasks/$TaskId"
$folders = @(
    $taskRoot,
    (Join-Path $taskRoot "context"),
    (Join-Path $taskRoot "artifacts"),
    (Join-Path $taskRoot "notes"),
    (Join-Path $taskRoot "logs")
)

foreach ($folder in $folders) {
    if (-not (Test-Path $folder)) {
        New-Item -Path $folder -ItemType Directory -Force | Out-Null
    }
}

$metaFile = Join-Path $taskRoot "task-meta.json"
if (-not (Test-Path $metaFile)) {
    $meta = [ordered]@{
        task_id = $TaskId
        owner = $Owner
        created_at = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")
        status = "created"
    }
    $meta | ConvertTo-Json -Depth 5 | Set-Content -Path $metaFile -Encoding UTF8
}

$readme = Join-Path $taskRoot "README.md"
if (-not (Test-Path $readme)) {
    @(
        "# Task Workspace: $TaskId",
        "",
        "- owner: $Owner",
        "- created_at: $((Get-Date).ToString("yyyy-MM-dd HH:mm:ss"))",
        "",
        "## Purpose",
        "Use this isolated folder for one task only to reduce cross-task context conflicts.",
        "",
        "## Structure",
        "- context/: compact context and checkpoints for this task",
        "- artifacts/: outputs generated by task",
        "- notes/: task notes",
        "- logs/: task-specific logs"
    ) | Set-Content -Path $readme -Encoding UTF8
}

$logScript = Join-Path $PSScriptRoot "Append-ProcessLog.ps1"
& $logScript -TaskId $TaskId -Stage "workspace" -Event "task_workspace_created" -Summary "workspace created at workspaces/tasks/$TaskId" -Root $Root | Out-Null

Write-Output "OK: workspace ready at $taskRoot"

